spring:
    datasource:
      url: jdbc:mysql://localhost:3306/sakila
      username: root
      password:

jwt:
  expiration: 2592000
  secretKey: VzzO3+vn3QqsXwTkp982RniBlw+t6PwgIKMX+OMW+78=
api:
  prefix: api