spring:
    datasource:
      url: jdbc:mysql://localhost:3306/sakila
      username: root
      password:

jwt:
  expiration: 2592000
  secretKey: VC9eQ+bA5ZmvtWtNtGSsZgfEkbYeDUeco6qaZv4sYRU=
api:
  prefix: api