spring:
    datasource:
      url: jdbc:mysql://localhost:3306/sakila
      username: root
      password:
api:
  prefix: api
server:
  port: 8081

jwt:
  expiration: 120000
  secretKey: 4fWORaSb7eZdTvMOxMiBhQl1hnT04/ozmC5cYFiPr00=